# mosquitto.conf

# Port for TLS-connection
# Used protocol mqtt
listener 8883
protocol mqtt

allow_anonymous false
password_file /mosquitto/secure/pwfile
# activate authorization
acl_file /mosquitto/secure/acl


#Path to cetificates for TLS connection in
# container
cafile /mosquitto/config/certs/ca.crt
certfile /mosquitto/config/certs/mqtt.crt
keyfile /mosquitto/config/certs/mqtt.key