services:
  webapp:
    build: .
    container_name: backend
    restart: always
    environment:
      - DB_HOST=mariadb
      - DB_WRITE_USER=websrv_write
      - DB_WRITE_PASSWORD=pass-0123-iot
      - DB_READ_USER=websrv_read
      - DB_READ_PASSWORD=pass-0123-client
      - DB_NAME=myapp
      - PORT=3000
      - API_KEY=api_key
    depends_on:
      db:
        condition: service_healthy
      keycloak_web:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: mariadb:latest
    command: --event-scheduler=ON
    container_name: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=root_password
      - MARIADB_DATABASE=myapp
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password
    volumes:
      - mariadb-data:/var/lib/mysql
      - /mariadb/conf.d:/etc/mysql/conf.d:ro
      - ./mariadb:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      app-network:
        aliases:
          - maria

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    ports:
      - "8883:8883"
    volumes:
      - ./mosquitto/config:/mosquitto/config:rw
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/log:/mosquitto/log:rw
      - ./mosquitto/secure:/mosquitto/secure:ro
      - /etc/timezone:/etc/timezone:ro
      - /set/localtime:/etc/localtime:ro
    restart: unless-stopped
    networks:
      sensor-network:
        aliases:
          - mqtt.local

  nginx:
    image: owasp/modsecurity-crs:nginx
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    environment:
      - PARANOIA=1
      - BACKEND=http://webapp:3000
      - PROXY_SSL=off
      - MSG="ModSecurity Attack Detected"
    volumes:
      - ./nginx/certs/www_key.key:/etc/nginx/certs/www_key.key:ro
      - ./nginx/certs/www_cert.cert:/etc/nginx/certs/www_cert.cert:ro
      - ./nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template:ro
    networks:
      app-network:
    depends_on:
      - webapp

  keycloak_web:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: keycloak_web
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8443
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_PROXY: edge
      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_RELATIVE_PATH: /auth
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak/iot-realm.json:/opt/keycloak/data/import/iot-realm.json:ro
    command: start-dev --http-port 8080 --import-realm
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080 && echo -e 'GET /auth/health/ready HTTP/1.1\r\nHost: localhost\r\n\r' >&3 && grep -q '200 OK' <&3" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 40s
    ports:
      - "8443:8080"
    networks:
      - app-network

  controller:
    build: sensor-net/
    restart: unless-stopped
    volumes:
      - ./sensor-data/ca.crt:/ca.crt:ro
    depends_on:
      - mqtt
      - nginx
    extra_hosts:
      - "www.lab.local:host-gateway"
    networks:
      sensor-network:

networks:
  app-network:
    driver: bridge
  sensor-network:
    driver: bridge

volumes:
  mariadb-data:
  keycloak_data: