# mosquitto.conf

#Client needs no certificate
require_certificate false
# Disable anonymous access
allow_anonymous false
password_file /mosquitto/secure/pwfile
# activate authorization
acl_file /mosquitto/secure/acl

# Port for TLS-connection
# Used protocol mqtt
listener 8883
protocol mqtt
#Path to cetificates for TLS connection in
# container
cafile /mosquitto/config/certs/ca.crt
certfile /mosquitto/config/certs/mqtt.crt
keyfile /mosquitto/config/certs/mqtt.key
#Client needs no certificate
require_certificate false
#CN field for client not needed
use_identity_as_username false