SecRuleEngine On #Regelwerk aktiv
SecRequestBodyAccess On #Request-Body prüfen
SecResponseBodyAccess Off #Reponse-Body nicht prüfen

SecAuditEngine RelevantOnly
SecAuditLog /dev/stdout
SecAuditLogFormat JSON

SecTmpDir /tmp #Temporäre Datenverarbeitung
SecDataDir /tmp #Temporäre Datenverarbeitung
#Unicode-Normalisierung
SecUnicodeMapFile
/etc/nginx/modsecurity/unicode.mapping 20127
# ModSecurity Core Rule Set (CRS) einbinden
Include /etc/nginx/modsecurity/crs-setup.conf
Include /etc/nginx/modsecurity/crs-rules/*.conf