server {
    listen 443 ssl;
    server_name www.lab.local; #Reverse Proxy
    #nginx Zertifikat und private Key
    ssl_certificate /etc/nginx/certs/www_cert.cert;
    ssl_certificate_key /etc/nginx/certs/www_key.key;
    location / {
        proxy_pass https://localhost:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_ssl_server_name on;
        proxy_ssl_name www.lab.local;
        proxy_ssl_trusted_certificate /etc/nginx/certs/ca.cert;
        proxy_ssl_verify on;
    }
}