server {
    listen 443 ssl;
    server_name www.lab.local;

    ssl_certificate /etc/nginx/certs/www_cert.cert;
    ssl_certificate_key /etc/nginx/certs/www_key.key;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    location / {
        proxy_pass https://backend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_ssl_server_name on;
        proxy_ssl_name www.lab.local;
    }
}