events {}

http {
    ssl_protocols TLSv1.2 TLSv1.3;

    server {
        listen 443 ssl;
        server_name www.lab.local; #Reverse Proxy
        #nginx Zertifikat und private Key
        ssl_certificate /certs/www_cert;
        ssl_certificate_key /certs/www_key;
        location / {
            proxy_pass https://localhost:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_ssl_server_name on;
            proxy_ssl_name websrv.lab.local;
            proxy_ssl_trusted_certificate /certs/ca_cert;
            proxy_ssl_verify on;
        }
    }
}